import os

ELEVENLABS_API_KEY = ""
IMAGEKIT_PRIVATE_KEY = os.getenv("IMAGEKIT_PRIVATE_KEY", "private_4EQ5nQpYtMllmHEQVSLf7B1vpMY=")
IMAGEKIT_UPLOAD_FOLDER = os.getenv("IMAGEKIT_UPLOAD_FOLDER", "ai-reels")